name: Build and Release EXE

on:
  push:
    branches:
      - main  # Change if needed

permissions:
  contents: write  # Required to create a release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile src/program/main.py --name r6sync
          echo "Build complete. Checking dist directory:"
          dir dist

      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: r6sync-exe
          path: dist/r6sync.exe

  release:
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      contents: write  # Required for creating a release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: r6sync-exe
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/r6sync.exe
          tag_name: r6sync-v1.0.${{ github.run_number }}  # Custom tag format
          name: r6sync v1.0.${{ github.run_number }}  # Custom release name
          body: "Automatically generated release for r6sync."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
